name = "cf-image-hosting"
compatibility_date = "2023-12-01"
main = "src/index.ts"
vars = { API_HOST = "https://telegra.ph" }

[env.dev.vars]
API_HOST = "https://telegraph.mingming.dev"

[site]
bucket = "./src"
